from extract_images_from_pdf_afip_factura_and_decode import extract_images_from_pdf_afip_factura_and_decode

print(extract_images_from_pdf_afip_factura_and_decode('./sample_files/2000005044986390.pdf'))